export enum ANIME_SEASONS {
  WINTER = "Winter",
  SPRING = "Spring",
  SUMMER = "Summer",
  FALL = "Fall",
}

export const ANIME_SEASONS_MAPPING = {
  // JANUARY, FEBRUARY, MARCH
  0: ANIME_SEASONS.WINTER,
  1: ANIME_SEASONS.WINTER,
  2: ANIME_SEASONS.WINTER,
  // APRIL, MAY, JUNE
  3: ANIME_SEASONS.SPRING,
  4: ANIME_SEASONS.SPRING,
  5: ANIME_SEASONS.SPRING,
  // JULY, AUGUST, SEPTEMBER
  6: ANIME_SEASONS.SUMMER,
  7: ANIME_SEASONS.SUMMER,
  8: ANIME_SEASONS.SUMMER,
  // OCTOBER, NOVEMBER, DECEMBER
  9: ANIME_SEASONS.FALL,
  10: ANIME_SEASONS.FALL,
  11: ANIME_SEASONS.FALL,
};
